---
services:
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --set redpanda.auto_create_topics_enabled=true
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    networks:
      default:
        aliases:
          - redpanda
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 15s
      retries: 10
    # Requires docker-compose 2.30 or later
    post_start:
      - command: /bin/bash -c "rpk topic create test logs-unknown || true"

  minio:
    image: quay.io/minio/minio
    command:
      - server
      - /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./test/bucket:/data
    environment:
      - MINIO_ROOT_USER=hotdog
      - MINIO_ROOT_PASSWORD=hotdoggin
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9000"]
      interval: 1s
      timeout: 1s
      retries: 10

  mc:
    image: quay.io/minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/bash -c "mc alias set minio http://minio:9000/ hotdog hotdoggin && mc mb minio/hotdog"
