---
version: '3'
services:
  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --set redpanda.auto_create_topics_enabled=true
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    networks:
      default:
        aliases:
          - redpanda
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 15s
      retries: 10
    # Requires docker-compose 2.30 or later
    post_start:
      - command: rpk topic create test logs-unknown

  localstack:
    image: localstack/localstack:0.13.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
