#!/bin/sh -xe
export endpoint_url=http://localhost:9000
export aws_allow_http=true
export access_key_id=hotdog
export secret_access_key=hotdoggin
export RUST_LOG=info
export SMOL_THREADS=4

#exec cargo run --release -- -c hotdog-parquet.yml
perf record --call-graph dwarf -- ./target/debug/hotdog -c ./hotdog-parquet.yml
